### ISSUE TITLE
Publish this gem to rubygems.org

### ISSUE THREAD

**Issue by zfhui** [immateriel/im_onix#76]
Hi, 👋 
I’m a backend developer at Blinkist and we just currently became interested in this gem. We’ve been trying it out for our own purposes and it has been working pretty well for us. So thanks a lot for creating and maintaining this open source project! 

Here comes my question. Since we are most likely going to build some of our business logic using your gem, we’ve been wondering whether you have any plans to publish it to https://rubygems.org to make it official? There are already a few gems on rubygems.com which deal with ONIX files, but none of them is that well maintained as yours. 

Cheers from Berlin, 
Fei

**Comment by julbouln** [comment]
Hi,

Thank you very much for your message. We are glad that it fit your needs ! Do not hesitate to contribute if you add something useful.
You're right and it is now something done thanks to @bergalath :
https://rubygems.org/gems/im_onix

Best regards
