### ISSUE TITLE
ISBN helpers on Onix 2.1 products

### ISSUE THREAD

**Issue by Wylan** [immateriel/im_onix#85]
Hi,

This looks like a really helpful gem! I've experimenting with parsing a Onix 2.1 message and noticed that the ISBN helpers (`IsbnMethods`) aren't included in the `ONIX::ONIX21::Product` class. 

https://github.com/immateriel/im_onix/blob/e9bbec08ae6846fdb4448ae912d9f336a8299013/lib/onix/onix21.rb#L313-L316

Vs.

https://github.com/immateriel/im_onix/blob/e9bbec08ae6846fdb4448ae912d9f336a8299013/lib/onix/product.rb#L294-L297

I've tried including the module in my own local copy and it seems they work out of the box, I'm happy to make a PR to include them, although it seems kind of silly for a single line 😆

**Comment by julbouln** [comment]
PR are welcome ! Even for one line, do not hesitate to propose it.
